version: '3'

dotenv: ['.env']

tasks:
  build:
    cmds:
      - scripts/build.sh

  json:
    deps:
      - build
    cmds:
      - yq '. | to_json' ${BUILD_PATH}/${CV}.yaml > ${BUILD_PATH}/${CV}.json

    skill_by_level:
      yq '.skills[] | select(.level == "{{.CLI_ARGS}}") | .name' ${SRC_PATH}/skills.yaml
